name: Testando módulo Terraform
run-name: ${{ github.actor }} iniciou o teste do módulo terraform.
on:
    push:
jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Latest version of Terraform Install
          uses: hashicorp/setup-terraform@v3

        - name: Terraform init
          run: terraform init

        - name: Check Terraform formatting
          run: terraform fmt -recursive -check

        - name: Render terraform docs inside README.md
          uses: terraform-docs/gh-actions@v1.4.1
          with:
            working-dir: .
            output-file: README.md
            output-method: inject
            git-push: "false"
            fail-on-diff: "true"